#!/bin/bash

function createTrafficManagement() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/trafficManagement.traffic.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-trafficManagement --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-trafficManagement.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-trafficManagement.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-trafficManagement.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-trafficManagement.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy trafficManagement's CA cert to trafficManagement's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem" "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/msp/tlscacerts/ca.crt"

  # Copy trafficManagement's CA cert to trafficManagement's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem" "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/tlsca/tlsca.trafficManagement.traffic.com-cert.pem"

  # Copy trafficManagement's CA cert to trafficManagement's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/ca"
  cp "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem" "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/ca/ca.trafficManagement.traffic.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-trafficManagement --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-trafficManagement --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-trafficManagement --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-trafficManagement --id.name trafficManagementadmin --id.secret trafficManagementadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-trafficManagement -M "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-trafficManagement -M "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/tls" --enrollment.profile tls --csr.hosts peer0.trafficManagement.traffic.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com/tls/server.key"

  echo "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-trafficManagement -M "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/msp/config.yaml"

  echo "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-trafficManagement -M "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/tls" --enrollment.profile tls --csr.hosts peer1.trafficManagement.traffic.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-trafficManagement -M "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/users/User1@trafficManagement.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/users/User1@trafficManagement.traffic.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://trafficManagementadmin:trafficManagementadminpw@localhost:7054 --caname ca-trafficManagement -M "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/users/Admin@trafficManagement.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/trafficManagement/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/trafficManagement.traffic.com/users/Admin@trafficManagement.traffic.com/msp/config.yaml"
}

function createMVD() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/mvd.traffic.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/mvd.traffic.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-mvd --tls.certfiles "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-mvd.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-mvd.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-mvd.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-mvd.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/mvd.traffic.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy mvd's CA cert to mvd's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/mvd.traffic.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem" "${PWD}/organizations/peerOrganizations/mvd.traffic.com/msp/tlscacerts/ca.crt"

  # Copy mvd's CA cert to mvd's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/mvd.traffic.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem" "${PWD}/organizations/peerOrganizations/mvd.traffic.com/tlsca/tlsca.mvd.traffic.com-cert.pem"

  # Copy mvd's CA cert to mvd's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/mvd.traffic.com/ca"
  cp "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem" "${PWD}/organizations/peerOrganizations/mvd.traffic.com/ca/ca.mvd.traffic.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-mvd --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-mvd --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-mvd --id.name mvdadmin --id.secret mvdadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-mvd -M "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/mvd.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-mvd -M "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/tls" --enrollment.profile tls --csr.hosts peer0.mvd.traffic.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-mvd -M "${PWD}/organizations/peerOrganizations/mvd.traffic.com/users/User1@mvd.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/mvd.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/mvd.traffic.com/users/User1@mvd.traffic.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://mvdadmin:mvdadminpw@localhost:8054 --caname ca-mvd -M "${PWD}/organizations/peerOrganizations/mvd.traffic.com/users/Admin@mvd.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/mvd/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/mvd.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/mvd.traffic.com/users/Admin@mvd.traffic.com/msp/config.yaml"
}


function createLawEnforcement() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/lawEnforcement.traffic.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-lawEnforcement --tls.certfiles "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-lawEnforcement.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-lawEnforcement.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-lawEnforcement.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-lawEnforcement.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy lawEnforcement's CA cert to lawEnforcement's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem" "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/msp/tlscacerts/ca.crt"

  # Copy lawEnforcement's CA cert to lawEnforcement's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem" "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/tlsca/tlsca.lawEnforcement.traffic.com-cert.pem"

  # Copy lawEnforcement's CA cert to lawEnforcement's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/ca"
  cp "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem" "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/ca/ca.lawEnforcement.traffic.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-lawEnforcement --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-lawEnforcement --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-lawEnforcement --id.name lawEnforcementadmin --id.secret lawEnforcementadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-lawEnforcement -M "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-lawEnforcement -M "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/tls" --enrollment.profile tls --csr.hosts peer0.lawEnforcement.traffic.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-lawEnforcement -M "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/users/User1@lawEnforcement.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/users/User1@lawEnforcement.traffic.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://lawEnforcementadmin:lawEnforcementadminpw@localhost:11054 --caname ca-lawEnforcement -M "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/users/Admin@lawEnforcement.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/lawEnforcement/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/lawEnforcement.traffic.com/users/Admin@lawEnforcement.traffic.com/msp/config.yaml"
}

function createInsuranceCompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/insuranceCompany.traffic.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7066 --caname ca-insuranceCompany --tls.certfiles "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7066-ca-insuranceCompany.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7066-ca-insuranceCompany.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7066-ca-insuranceCompany.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7066-ca-insuranceCompany.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/msp/config.yaml"

  # Copy insuranceCompany's CA cert to msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/msp/tlscacerts/ca.crt"

  # Copy insuranceCompany's CA cert to tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/tlsca/tlsca.insuranceCompany.traffic.com-cert.pem"

  # Copy insuranceCompany's CA cert to ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/ca"
  cp "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/ca/ca.insuranceCompany.traffic.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-insuranceCompany --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-insuranceCompany --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-insuranceCompany --id.name insuranceCompanyadmin --id.secret insuranceCompanyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7066 --caname ca-insuranceCompany -M "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7066 --caname ca-insuranceCompany -M "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/tls" --enrollment.profile tls --csr.hosts peer0.insuranceCompany.traffic.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7066 --caname ca-insuranceCompany -M "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/users/User1@insuranceCompany.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/users/User1@insuranceCompany.traffic.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://insuranceCompanyadmin:insuranceCompanyadminpw@localhost:7066 --caname ca-insuranceCompany -M "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/users/Admin@insuranceCompany.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insuranceCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insuranceCompany.traffic.com/users/Admin@insuranceCompany.traffic.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/traffic.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/traffic.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/traffic.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/traffic.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/traffic.com/msp/tlscacerts/tlsca.traffic.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/traffic.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/traffic.com/tlsca/tlsca.traffic.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/traffic.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls" --enrollment.profile tls --csr.hosts orderer.traffic.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/msp/tlscacerts/tlsca.traffic.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/traffic.com/users/Admin@traffic.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/traffic.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/traffic.com/users/Admin@traffic.com/msp/config.yaml"
}

createTrafficManagement
createMVD
createLawEnforcement
createInsuranceCompany
createOrderer