version: '3.7'

volumes:
  orderer.traffic.com:
  peer0.trafficManagement.traffic.com:
  peer1.trafficManagement.traffic.com:
  peer0.mvd.traffic.com:
  peer0.lawEnforcement.traffic.com:
  peer0.insuranceCompany.traffic.com:



networks:
  Traffic:
    name: fabric_traffic

services: 

  orderer.traffic.com:
    container_name: orderer.traffic.com
    image: hyperledger/fabric-orderer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.traffic.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/traffic.com/orderers/orderer.traffic.com/tls/:/var/hyperledger/orderer/tls
      - orderer.traffic.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - Traffic

  couchdb0:
    container_name: couchdbtrafficManagement
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - Traffic

  peer0.trafficManagement.traffic.com:
    container_name: peer0.trafficManagement.traffic.com
    image: hyperledger/fabric-peer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_traffic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.trafficManagement.traffic.com
      - CORE_PEER_ADDRESS=peer0.trafficManagement.traffic.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.trafficManagement.traffic.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.trafficManagement.traffic.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.trafficManagement.traffic.com:7051
      - CORE_PEER_LOCALMSPID=TrafficManagementMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.trafficManagement.traffic.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0trafficManagement"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer0.trafficManagement.traffic.com:/etc/hyperledger/fabric
      - peer0.trafficManagement.traffic.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    depends_on:
      - couchdb0
    networks:
      - Traffic

  peer1.trafficManagement.traffic.com:
    container_name: peer1.trafficManagement.traffic.com
    image: hyperledger/fabric-peer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_traffic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.trafficManagement.traffic.com
      - CORE_PEER_ADDRESS=peer1.trafficManagement.traffic.com:8050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8050
      - CORE_PEER_CHAINCODEADDRESS=peer1.trafficManagement.traffic.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.trafficManagement.traffic.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.trafficManagement.traffic.com:8051
      - CORE_PEER_LOCALMSPID=TrafficManagementMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.trafficManagement.traffic.com:9447
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1trafficManagement"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/trafficManagement.traffic.com/peers/peer1.trafficManagement.traffic.com:/etc/hyperledger/fabric
      - peer1.trafficManagement.traffic.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8050:8050
      - 9447:9447
    depends_on:
      - couchdb0
    networks:
      - Traffic

  couchdb1:
    container_name: couchdbmvd
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    networks:
      - Traffic

  peer0.mvd.traffic.com:
    container_name: peer0.mvd.traffic.com
    image: hyperledger/fabric-peer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_traffic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.mvd.traffic.com
      - CORE_PEER_ADDRESS=peer0.mvd.traffic.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.mvd.traffic.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mvd.traffic.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.mvd.traffic.com:9051
      - CORE_PEER_LOCALMSPID=MVDMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.mvd.traffic.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0mvd"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/mvd.traffic.com/peers/peer0.mvd.traffic.com:/etc/hyperledger/fabric
      - peer0.mvd.traffic.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051 
      - 9445:9445
    depends_on:
      - couchdb1
    networks:
      - Traffic

  couchdb2:
    container_name: couchdblawEnforcement
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984"
    networks:
      - Traffic

  peer0.lawEnforcement.traffic.com:
    container_name: peer0.lawEnforcement.traffic.com
    image: hyperledger/fabric-peer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      # - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_traffic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.lawEnforcement.traffic.com
      - CORE_PEER_ADDRESS=peer0.lawEnforcement.traffic.com:11051
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.lawEnforcement.traffic.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lawEnforcement.traffic.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lawEnforcement.traffic.com:11051
      - CORE_PEER_LOCALMSPID=LawEnforcementMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.lawEnforcement.traffic.com:9446
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0lawEnforcement"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s  
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb2    
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock      
      - ../organizations/peerOrganizations/lawEnforcement.traffic.com/peers/peer0.lawEnforcement.traffic.com:/etc/hyperledger/fabric        
      - peer0.lawEnforcement.traffic.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 11051:11051
      - 9446:9446
    networks:
      - Traffic
  
  couchdb3:
    container_name: couchdbinsuranceCompany
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9986:5984"
    networks:
      - Traffic

  peer0.insuranceCompany.traffic.com:
    container_name: peer0.insuranceCompany.traffic.com
    image: hyperledger/fabric-peer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      # - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_traffic
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.insuranceCompany.traffic.com
      - CORE_PEER_ADDRESS=peer0.insuranceCompany.traffic.com:7044
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7044
      - CORE_PEER_CHAINCODEADDRESS=peer0.insuranceCompany.traffic.com:7066
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7066
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insuranceCompany.traffic.com:7044
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insuranceCompany.traffic.com:7044
      - CORE_PEER_LOCALMSPID=InsuranceCompanyMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.insuranceCompany.traffic.com:9955
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0insuranceCompany"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s  
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb3    
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock      
      - ../organizations/peerOrganizations/insuranceCompany.traffic.com/peers/peer0.insuranceCompany.traffic.com:/etc/hyperledger/fabric        
      - peer0.insuranceCompany.traffic.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7044:7044
      - 9955:9955
    networks:
      - Traffic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.4
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
    depends_on:
      - peer0.trafficManagement.traffic.com
      - peer0.mvd.traffic.com
      - peer0.lawEnforcement.traffic.com
      - peer0.insuranceCompany.traffic.com
    networks:
      - Traffic